namespace NgoFund.Contracts.Applicants;

public record UpdateApplicantRequest(
    string? MembershipNumber,
    string FullName,
    string? FatherOrHusbandName,
    string Cnic,
    string Gender,
    DateOnly? DateOfBirth,
    string? MaritalStatus,
    string? Phone,
    string? AlternatePhone,
    string? Email,
    string? Address,
    string? City,
    string? District,
    string? Province,
    string? Occupation,
    decimal? MonthlyIncome,
    int? DependentsCount,
    int? HouseholdSize,
    bool IsBlacklisted,
    string? BlacklistReason,
    string? Notes,
    string? GrandfatherName = null,
    string? Surname = null,
    string? AncestralVillage = null,
    string? FatherMembershipNumber = null,
    string? WhatsappNumber = null);
